[font]
size = 14.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "buttonless"
opacity = 0.999

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
  { mods="Command" , key="j", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -D"]} },
  { mods="Command" , key="k", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -U"]} },
  { mods="Command" , key="h", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -L"]} },
  { mods="Command" , key="l", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -R"]} },
  { mods="Control|Shift" , key="m", action="ToggleMaximized" },
  { mods="Control|Shift" , key="i", action="IncreaseFontSize" },
  { mods="Control|Shift" , key="d", action="DecreaseFontSize" }
]

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal.shell]
program = "/opt/homebrew/bin/nu"
