[font]
size = 16.0

[font.normal]
family = "FiraCode Nerd Font"

[window]
decorations = "buttonless"
opacity = 0.999
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

[keyboard]
bindings = [
  { mods="Command" , key="j", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -D"]} },
  { mods="Command" , key="k", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -U"]} },
  { mods="Command" , key="h", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -L"]} },
  { mods="Command" , key="l", command={program="sh", args=["-c", "$HOME/.bin/tmux-vim-select-pane -R"]} }
]

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]
