#!/bin/bash

USER_NAME=$(git config user.name)
USER_EMAIL=$(git config user.email)

PERMANENTLY_APPROVED=$(git rev-parse --show-toplevel)/.git/.name_and_email_approved

if [ -f $PERMANENTLY_APPROVED ]; then
    exit 0
fi

echo "Is this user correct for this repository?"
echo "  $USER_NAME <$USER_EMAIL>"
echo
echo "If it is not correct, please fix it with:"
echo "  git config user.name 'Your Name'"
echo "  git config user.email 'Your Email'"
echo

exec < /dev/tty

read -p "¿Do you want to continue with the commit? (y/n): " choice

case "$choice" in
    y|Y )
        touch $PERMANENTLY_APPROVED
        echo "Nice!"
        echo
        ;;
    n|N ) 
        echo "Aborted"
        echo
        exit 1
        ;;
    * ) 
        echo "Aborted"
        echo
        exit 1
        ;;
esac

