# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Bootstrap
source $HOME/.config/zsh/exports.sh
source $HOME/.config/zsh/aliases.sh
source $HOME/.config/zsh/functions.sh

# Homebrew
if [ "$(arch)" = "arm64" ];
then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  eval "$(/usr/local/bin/brew shellenv)"
fi

# Google cloud
if [ -d "$HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk" ]
then
    source $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
    source $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc  
fi

# ZSH Ops
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FCNTL_LOCK

# Antidote
# https://getantidote.github.io/
# brew install antidote
source $HOMEBREW_PREFIX/Cellar/antidote/1.9.4/share/antidote/antidote.zsh
antidote load $HOME/.config/zsh/plugins.txt

# Tmux fix
bindkey -e

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f $HOME/.config/zsh/p10k.zsh ]] || source $HOME/.config/zsh/p10k.zsh

# Completion
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
autoload -U compinit && compinit -i
bindkey "^I" complete-word

# bun completions
[ -s $HOME/.bun/_bun ] && source $HOME/.bun/_bun

eval "$(zoxide init zsh)"

# bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
eval "$(atuin init zsh)"
