#!/bin/bash

set -e

cmd="$(/opt/homebrew/bin/tmux display -p '#{pane_current_command}')"
cmd="$(basename "$cmd" | tr A-Z a-z)"
pane_count="$(/opt/homebrew/bin/tmux list-panes | wc -l)"

# if [ "${cmd}" = "nvim" ] || [ "$pane_count" -eq 1 ]; then
#   direction="$(echo "${1#-}" | tr 'lLDUR' '\\hjkl')"
#   /opt/homebrew/bin/tmux send-keys "C-S-$direction"
# else
  /opt/homebrew/bin/tmux select-pane "$@"
# fi

