# imports
source $HOME/.config/zsh/exports.sh
source $HOME/.config/zsh/aliases.sh
source $HOME/.config/zsh/functions.sh

# homebrew (brew) installation depends on the architecture
if [ "$(arch)" = "arm64" ];
then
  eval "$(/opt/homebrew/bin/brew shellenv)"
else
  eval "$(/usr/local/bin/brew shellenv)"
fi

# google cloud configuration and auto-completion
if [ -d "$HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk" ]
then
    source $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
    source $HOMEBREW_PREFIX/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc  
fi

# zsh options
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FCNTL_LOCK

# antidote: zsh plugin manager
# https://getantidote.github.io/
# brew install antidote
ANTIDOTE_VERSION=1.9.7
ANTIDOTE_SCRIPT=$HOMEBREW_PREFIX/Cellar/antidote/${ANTIDOTE_VERSION}/share/antidote/antidote.zsh
if [[ -r $ANTIDOTE_SCRIPT ]]; then
  source $ANTIDOTE_SCRIPT
  antidote load $HOME/.config/zsh/plugins.txt
else
  echo "Antidote ${ANTIDOTE_VERSION} not present."
  echo "Consider running brew upgrade."
fi

# fix for tmux
bindkey -e

# zsh-completions configuration
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
autoload -U compinit && compinit -i
bindkey "^I" complete-word

# zoxide: cd replacement using "z"
# brew install zoxide
eval "$(zoxide init zsh)"

# atuin: shell history tool
# bash <(curl --proto '=https' --tlsv1.2 -sSf https://setup.atuin.sh)
eval "$(atuin init zsh --disable-up-arrow)"

# fnm: node version manager
# brew install fnm
eval "$(fnm env --use-on-cd --shell zsh)"
eval "$(fnm completions --shell zsh)"

# starship
# brew install starship
eval "$(starship init zsh)"
