# vim:fileencoding=utf-8:foldmethod=marker

include theme.conf

font_family      FiraCode Nerd Font Mono Med
font_size 16.0
disable_ligatures never

hide_window_decorations yes
# hide_window_decorations titlebar-only

enable_audio_bell no
cursor_shape     beam

# url_color #b96507
# url_style curly

# cursor_shape block
# cursor_beam_thickness 1.8

# tab_bar_style powerline
# tab_powerline_style round

